window.launchContent = {
  schemaVersion: "1.0",
  release: {
    id: "release:mvp-2026-08",
    label: "Foundation Edition",
    version: "0.9",
    status: "beta_review",
    updatedAt: "2026-08-16",
    evidenceReviewedAt: "2026-08-01",
    reviewDue: "2027-08-01"
  },
  plays: [
    {id:"play:01",number:1,slug:"establish-vision-and-principles",phase:"plan",title:"Establish Vision and Principles",summary:"Align leadership around public health value, responsible-use principles, priorities, and boundaries.",purpose:"Align leadership around the public health problems AI may help address, the value it should create, and the boundaries it must not cross.",output:"A shared AI vision, responsible-use principles, priorities, and explicit prohibitions.",tool:{id:"starter-tool:01",title:"AI Vision & Principles Workshop",purpose:"A structured leadership conversation that captures mission alignment, public value, principles, priority problems, concerns, and non-negotiable boundaries."},people:["Executive leadership","Program leaders","Legal and privacy","Equity and community representatives","IT and data leadership"],questions:["What public health value should AI create?","Which uses conflict with agency values or authority?","What must always remain a human decision?"],evidence:"Consensus-based",audiences:["health_executive","governance_risk_lead","informatics_director"]},
    {id:"play:02",number:2,slug:"assess-readiness",phase:"plan",title:"Assess Readiness",summary:"Understand strengths and gaps across leadership, data, workforce, equity, privacy, and security.",purpose:"Build a realistic picture of the department's capacity to adopt and govern AI before committing to projects.",output:"A readiness profile, priority gaps, and a sequenced set of improvement actions.",tool:{id:"starter-tool:02",title:"AI Readiness Self-Assessment",purpose:"A guided assessment of leadership, governance, data, technology, workforce, equity, privacy, security, and implementation capacity."},people:["Leadership","Program operations","IT and security","Data owners","Workforce and equity leads"],questions:["Where is the department already prepared?","Which gaps would make an AI project unsafe or unsustainable?","What should be addressed before a pilot?"],evidence:"Supported",audiences:["health_executive","informatics_director","program_manager"]},
    {id:"play:03",number:3,slug:"establish-governance",phase:"plan",title:"Establish Governance",summary:"Define authority, oversight, review pathways, and accountability before projects advance.",purpose:"Create a repeatable way to review, approve, monitor, pause, and retire AI-supported work.",output:"Defined authority, decision rights, review pathways, risk tiers, and oversight responsibilities.",tool:{id:"starter-tool:03",title:"AI Advisory Committee Charter",purpose:"A starter charter for purpose, membership, responsibilities, meeting cadence, escalation, and decision documentation."},people:["Executive sponsor","Program representatives","Legal, privacy, and security","Equity and communications","Data and technology reviewers"],questions:["Who can approve or stop an AI use?","What level of review does each risk tier require?","How will decisions and conditions be documented?"],evidence:"Consensus-based",audiences:["health_executive","governance_risk_lead","it_technical_lead"]},
    {id:"play:04",number:4,slug:"engage-stakeholders",phase:"plan",title:"Engage Stakeholders",summary:"Bring workforce, community, equity, and partner perspectives into decisions early.",purpose:"Bring affected staff, communities, partners, and missing perspectives into planning before decisions become difficult to change.",output:"A stakeholder map, engagement responsibilities, feedback plan, and record of what changed.",tool:{id:"starter-tool:04",title:"Stakeholder Mapping & RACI",purpose:"A worksheet for identifying affected groups and assigning responsible, accountable, consulted, and informed roles."},people:["Program and engagement leads","Community representatives","Equity and accessibility staff","Tribal partners where applicable","Communications"],questions:["Who is affected by the proposed use?","Whose data or experience may be missing?","How will feedback influence the decision?"],evidence:"Consensus-based",audiences:["program_manager","communications","equity_community_engagement"]},
    {id:"play:05",number:5,slug:"develop-the-workforce",phase:"plan",title:"Develop the Workforce",summary:"Build role-based capabilities, peer support, and practical confidence.",purpose:"Prepare staff and leaders with the role-specific knowledge, judgment, and support required for responsible adoption.",output:"A competency and training approach supported by champions, bridge roles, and peer learning.",tool:{id:"starter-tool:05",title:"AI Champion Designation & Role Guide",purpose:"A guide for selecting, preparing, and supporting staff who can help colleagues use approved AI practices responsibly."},people:["HR and workforce development","Training leads","Supervisors","AI champions","Program, data, and IT staff"],questions:["What must each role know or be able to do?","Where are the greatest competency gaps?","Who will support staff after training?"],evidence:"Emerging / supported",audiences:["workforce_training_lead","program_manager","health_executive"]},
    {id:"play:06",number:6,slug:"plan-for-change",phase:"plan",title:"Plan for Change",summary:"Prepare people, workflows, communications, and support for responsible adoption.",purpose:"Anticipate how new tools will affect roles, workflows, expectations, trust, and day-to-day operations.",output:"A change approach covering communications, training, workflow changes, support, and barriers.",tool:{id:"starter-tool:06",title:"Resistance & Barrier Identification",purpose:"A worksheet for surfacing operational, cultural, trust, workload, and adoption barriers before deployment."},people:["Change and communications leads","Supervisors","Affected staff","Training leads","AI champions"],questions:["What will change for each role?","What concerns or barriers could prevent safe adoption?","What support will staff need?"],evidence:"Supported",audiences:["program_manager","communications","workforce_training_lead"]},
    {id:"play:07",number:7,slug:"prioritize-use-cases",phase:"plan",title:"Prioritize Use Cases",summary:"Compare AI opportunities by value, feasibility, equity, and risk.",purpose:"Select AI opportunities based on public health value, feasibility, equity, sustainability, and risk—not novelty.",output:"A documented use-case inventory and prioritized set of candidates for governance review.",tool:{id:"starter-tool:07",title:"AI Use Case Intake & Triage Worksheet",purpose:"A structured intake covering purpose, workflow, data, users, affected populations, benefits, risks, readiness, and review pathway."},people:["Program owners","Governance reviewers","Data and IT","Equity, privacy, and security","Finance and procurement"],questions:["What problem are we solving?","Is AI appropriate for this workflow?","What evidence and safeguards are required before proceeding?"],evidence:"Consensus-based",audiences:["program_manager","informatics_director","governance_risk_lead"]},
    {id:"play:08",number:8,slug:"align-funding-and-procurement",phase:"build",title:"Align Funding and Procurement",summary:"Plan for lifecycle costs and responsible vendor or procurement decisions.",purpose:"Ensure approved priorities have sustainable resources and responsible acquisition pathways.",output:"A funding strategy, lifecycle cost assumptions, and procurement requirements.",tool:{id:"starter-tool:08",title:"Funding Strategy Starter Checklist",purpose:"A starter review of eligible funding, budget categories, sustainment, staffing, infrastructure, evaluation, and contingency needs."},people:["Finance and grants","Procurement","Program sponsors","IT and security","Legal and governance"],questions:["What will the full lifecycle cost?","Which procurement safeguards are required?","How will the work continue after pilot funding ends?"],evidence:"Authoritative guidance",audiences:["procurement_finance","health_executive","program_manager"]},
    {id:"play:09",number:9,slug:"develop-the-implementation-roadmap",phase:"build",title:"Develop the Implementation Roadmap",summary:"Sequence dependencies, owners, milestones, approvals, and decisions.",purpose:"Turn approved, resourced use cases into a practical sequence of work with accountable owners and decision gates.",output:"A roadmap with milestones, dependencies, owners, approvals, risks, and scale decisions.",tool:{id:"starter-tool:09",title:"AI Implementation Timeline",purpose:"A planning timeline for sequencing governance, data, procurement, testing, training, communications, deployment, and evaluation milestones."},people:["Project and program management","Technical and data leads","Governance","Change and training leads","Operational owners"],questions:["What must happen before the pilot begins?","Which dependencies are shared across projects?","What conditions should trigger a pause or revision?"],evidence:"Supported",audiences:["program_manager","informatics_director","it_technical_lead"]},
    {id:"play:10",number:10,slug:"execute-change-management",phase:"deploy",title:"Execute Change Management",summary:"Communicate, train, support adoption, and respond to staff feedback.",purpose:"Deliver the communications, training, support, and feedback processes planned for the new workflow.",output:"Prepared staff, visible support, tracked barriers, and adoption evidence.",tool:{id:"starter-tool:10",title:"Staff Communication & FAQ Template",purpose:"A plain-language template explaining what is changing, why, what AI will and will not do, staff responsibilities, and where to get help."},people:["Change leads","Supervisors","Communications","Training staff","Pilot users and champions"],questions:["Have affected roles completed preparation?","Do staff understand limitations and escalation?","How will emerging barriers be tracked and addressed?"],evidence:"Supported",audiences:["communications","workforce_training_lead","program_manager"]},
    {id:"play:11",number:11,slug:"pilot-and-deploy",phase:"deploy",title:"Pilot and Deploy",summary:"Test deliberately and confirm safeguards, readiness, and decision criteria.",purpose:"Test the workflow under controlled conditions and use evidence to decide whether to revise, scale, pause, or stop.",output:"A governed pilot, documented results, and an accountable go-live or scale decision.",tool:{id:"starter-tool:11",title:"Deployment Readiness Checklist",purpose:"A pre-launch check covering approval, validation, security, data, training, communications, support, monitoring, rollback, and decision criteria."},people:["Operational owner","IT and security","Data and validation leads","Governance","Change, evaluation, and support teams"],questions:["Are safeguards and human review working?","Does the workflow perform adequately in the local setting?","Is the department ready to respond when something fails?"],evidence:"Authoritative / supported",audiences:["it_technical_lead","informatics_director","program_manager"]},
    {id:"play:12",number:12,slug:"sustain-governance",phase:"govern",title:"Sustain Governance",summary:"Maintain oversight, decisions, documentation, and improvement after launch.",purpose:"Keep oversight active after approval and deployment as systems, vendors, policies, and risks change.",output:"Recurring reviews, current inventories, incident follow-up, documented decisions, and updated controls.",tool:{id:"starter-tool:12",title:"AI Governance Review Meeting Template",purpose:"A recurring agenda and decision record for system status, performance, incidents, policy changes, risks, conditions, and action owners."},people:["Governance body","System and program owners","Privacy and security","Legal and procurement","Equity and evaluation"],questions:["Are approval conditions still being met?","What has changed since the last review?","Should the use continue, change, pause, or retire?"],evidence:"Authoritative / consensus",audiences:["governance_risk_lead","health_executive","it_technical_lead"]},
    {id:"play:13",number:13,slug:"monitor-and-evaluate",phase:"govern",title:"Monitor and Evaluate",summary:"Track performance, equity, outcomes, emerging risks, and lessons learned.",purpose:"Determine whether AI-supported work remains reliable, equitable, useful, safe, and aligned with public health goals.",output:"Performance and equity monitoring, outcome findings, lessons learned, and improvement actions.",tool:{id:"starter-tool:13",title:"Continuous Improvement Log",purpose:"A simple record of findings, improvement actions, owners, deadlines, supporting evidence, escalation, and closure."},people:["Operational owners","Evaluation and quality staff","Equity staff","Data and technical reviewers","Governance and leadership"],questions:["Is performance stable across meaningful groups?","Is the workflow producing public health value?","What evidence requires improvement, escalation, or retirement?"],evidence:"Supported",audiences:["researcher","epidemiologist","governance_risk_lead"]}
  ]
};
