const view = new URLSearchParams(location.search).get("view") || "maturity";

const pages = {
  cases: {
    eyebrow: "Case Studies",
    title: "Learn from public health implementation experience.",
    lead: "Use public examples to examine decisions, safeguards, limitations, and questions that should be tested locally.",
    content: `<section class="panel playbook-overview"><h2>How to interpret these examples</h2><p>Case studies are learning resources, not endorsements or proof that the same approach will work in every jurisdiction. Compare authority, data, workforce, community, technology, procurement, and operational conditions before transferring a practice.</p></section>
      <div class="detail-card-list">
        <article class="panel"><p class="eyebrow">California Department of Public Health · Generative AI pilot</p><h2>Health care facility inspection documentation</h2><p><strong>Challenge:</strong> Inspectors must document findings clearly and connect observations to applicable requirements, a process that can be time-consuming and difficult to standardize.</p><p><strong>Approach:</strong> California identifies a pilot testing generative AI support for inspection-report drafting and regulatory linkage while inspectors retain professional judgment.</p><p><strong>Transferable lesson:</strong> AI-assisted drafting requires human verification of facts and citations, legally sufficient records, retention rules, bias review, and a clear prohibition on automatic findings or enforcement.</p><p><strong>Questions to test locally:</strong> Who validates generated language? What evidence is retained? What error threshold pauses use?</p><p><a href="https://www.genai.ca.gov/projects/health-care-facility-inspections/" target="_blank" rel="noopener noreferrer">Review the California project source →</a></p></article>
        <article class="panel"><p class="eyebrow">California Health and Human Services Agency · Language access</p><h2>AI-assisted translation and readability support</h2><p><strong>Challenge:</strong> Residents need timely, understandable, culturally appropriate health and social-services information across languages.</p><p><strong>Approach:</strong> California's public project materials describe generative AI as a potential first-draft aid, followed by qualified human review and editing.</p><p><strong>Transferable lesson:</strong> Translation speed cannot replace language access, cultural context, health literacy, accessibility, privacy, or approval by qualified reviewers.</p><p><strong>Questions to test locally:</strong> Which languages and content types are appropriate? Who is qualified to approve the result? How are corrections captured?</p><p><a href="https://www.genai.ca.gov/projects/language-access/" target="_blank" rel="noopener noreferrer">Review the California project source →</a></p></article>
        <article class="panel"><p class="eyebrow">Kansas Public Health Collaborative · Local health departments</p><h2>Public health AI playbook and operational tools</h2><p><strong>Challenge:</strong> Local health departments need practical guidance for communications, grant support, health literacy, campaign planning, and content review without creating privacy, quality, or trust risks.</p><p><strong>Approach:</strong> Kansas developed public-health-specific AI guidance, tools, frequently asked questions, and peer-learning support.</p><p><strong>Transferable lesson:</strong> Structured guidance can move agencies from informal experimentation toward approved uses, source verification, human review, accessibility, and documented accountability.</p><p><strong>Questions to test locally:</strong> Which uses are approved? What information is prohibited? Who verifies public-facing content?</p><p><a href="https://www.kansaspublichealthcollaborative.org/ai-in-public-health/" target="_blank" rel="noopener noreferrer">Review the Kansas resource →</a></p></article>
      </div>
      <section class="panel"><h2>Use the common case-study lens</h2><p>For every example, document the public health challenge, intended users, affected populations, data, workflow change, human decisions, claimed and measured outcomes, limitations, safeguards, source type, and evidence still needed.</p><div class="button-row"><a class="btn primary" href="resources.html">Review Evidence & Resources</a><a class="btn" href="feedback.html">Suggest a public health example</a></div></section>`
  },
  community: {
    eyebrow: "Community",
    title: "Help strengthen responsible public health AI practice.",
    lead: "Participate through structured review, corrections, evidence suggestions, implementation learning, and release updates.",
    content: `<div class="workflow-grid"><article class="card"><h2>Structured review</h2><p>Review released or completed-but-not-public materials for accuracy, clarity, usability, public health fit, accessibility, equity, role fit, and missing perspectives.</p></article><article class="card"><h2>Corrections and contributions</h2><p>Submit a correction, evidence source, implementation lesson, public health example, tool suggestion, accessibility concern, or practical barrier.</p></article><article class="card"><h2>Release updates</h2><p>Follow new public releases, material corrections, evidence updates, reviewer opportunities, and future public learning events.</p></article></div>
      <section class="panel"><h2>Who can participate</h2><p>Public health practitioners, executives, epidemiologists, informaticians, program managers, technical staff, communicators, researchers, educators, governance specialists, legal and privacy professionals, accessibility specialists, Tribal partners, and community representatives are welcome to apply.</p><h2>What reviewers can expect</h2><ol><li>Apply with your role, experience, and areas of interest.</li><li>Receive an invitation when a review matches your experience and current review capacity.</li><li>Review a defined item using structured questions and disclose relevant conflicts of interest.</li><li>Return practical comments by the stated date; reviewers are not required to endorse the material.</li><li>Receive acknowledgment only with permission. Completed-but-unreleased materials may not be redistributed.</li></ol><p>Reviewer participation is voluntary. Selection depends on topic fit, balance of perspectives, and available review capacity.</p><div class="button-row"><a class="btn primary" href="reviewer.html">Become a Reviewer</a><a class="btn" href="feedback.html">Share feedback or a correction</a></div></section>
      <section class="panel"><h2>Edition boundary</h2><p>The Foundation Edition provides public review, feedback, and update pathways. The interactive member forum, saved discussions, organization groups, and facilitated communities of practice are available through other editions or engagements.</p></section>`
  },
  contact: {
    eyebrow: "Contact Us",
    title: "Questions, implementation support, and partnership inquiries.",
    lead: "Choose the route that matches your question, correction, reviewer interest, partnership, or organizational implementation need.",
    content: `<div class="workflow-grid"><article class="card"><h2>Content feedback and corrections</h2><p>Report unclear language, broken links, evidence gaps, accessibility problems, or suggested improvements to a play, tool, module, case, or resource.</p><a href="feedback.html">Open the feedback form →</a></article><article class="card"><h2>Reviewer participation</h2><p>Apply to review materials related to your public health role or subject-matter experience.</p><a href="reviewer.html">Apply to become a reviewer →</a></article><article class="card"><h2>Implementation and training support</h2><p>Explore executive workshops, readiness and governance engagements, implementation cohorts, advisory support, workforce development, and sponsored multi-jurisdiction programs.</p><a href="consulting.html">View consulting offerings →</a></article></div>
      <section class="panel"><h2>Choose the right route</h2><ul><li><strong>General or content question:</strong> use the feedback form and identify the relevant page, play, tool, or topic.</li><li><strong>Consulting or organizational access:</strong> review the consulting offerings and describe the decision or implementation need.</li><li><strong>Partnership or sponsored program:</strong> use the consulting pathway and identify participating organizations, jurisdictions, or intended audience.</li><li><strong>Accessibility or technical issue:</strong> use the feedback form and include the page, device or browser, and what prevented access.</li></ul><div class="button-row"><a class="btn primary" href="consulting.html">Need More Help?</a><a class="btn" href="feedback.html">Send Feedback</a><a class="btn" href="reviewer.html">Become a Reviewer</a></div></section>
      <section class="panel"><h2>Protect sensitive information</h2><p>Do not submit protected health information, personally identifiable information, credentials, confidential agency information, procurement-sensitive information, or security details through public forms.</p></section>`
  }
};

if (view === "maturity") {
  document.title = "AI Maturity Model | Public Health AI Playbook Foundation Edition";
  document.querySelector("#main").innerHTML = window.MaturityModelTemplate.render({ edition: "foundation", assetPrefix: "../" });
} else if (view === "news") {
  document.title = "In the News | Public Health AI Playbook Foundation Edition";
  document.querySelector("#main").innerHTML = window.NewsFeedTemplate.render({ edition: "foundation" });
  window.NewsFeedTemplate.bind();
} else {
  const page = pages[view] || pages.cases;
  document.title = `${page.eyebrow} | Public Health AI Playbook Foundation Edition`;
  document.querySelector("#main").innerHTML = window.PlaybookTemplates.pageOpen({ title: page.title, lead: page.lead, eyebrow: page.eyebrow }) + `${page.content}</section>`;
}
