const modules=[
 {id:"int-100",code:"INT 100",title:"Introduction to AI for Public Health",level:"Introductory",summary:"Build a practical understanding of predictive, generative, analytic, and agentic AI in public health work.",objectives:["Distinguish common forms of AI used in public health","Explain appropriate roles for AI and accountable humans","Recognize why context, data quality, and workflow matter"],topics:["AI and machine learning basics","Public health applications","Human judgment and accountability","Common limitations and misconceptions"],exercise:"Identify one workflow where AI may help and one where it should not be used without substantial safeguards."},
 {id:"int-105",code:"INT 105",title:"All-Staff Safe AI Use and Approved Tools Awareness",level:"Introductory · 35–45 minutes",summary:"Apply department rules for approved tools, sensitive information, output review, escalation, and responsible day-to-day use.",objectives:["Recognize approved and unapproved AI environments","Protect PHI, PII, confidential, and sovereign data","Review outputs and escalate errors or concerns"],topics:["Approved-use boundaries","Data classification","Human review","Incident and concern reporting"],exercise:"Review three common staff scenarios and document the safe action, prohibited action, and escalation path for each."},
 {id:"int-190",code:"INT 190",title:"AI for Social Good",level:"Introductory",summary:"Examine how AI can support public value while avoiding technological solutionism and preventable harm.",objectives:["Connect AI proposals to a defined public health purpose","Consider benefits, burdens, access, and structural context","Distinguish public value from technological novelty"],topics:["Public value","Benefits and harms","Digital determinants of health","Responsible innovation"],exercise:"Write a public-value statement for a proposed use case that identifies beneficiaries, possible burdens, and alternatives."},
 {id:"int-200",code:"INT 200",title:"AI Use Case Intake and Triage Basics",level:"Applied foundational",summary:"Describe proposed AI uses clearly enough for preliminary value, risk, data, equity, and governance review.",objectives:["Define the problem before selecting technology","Document users, data, affected populations, and workflow","Recognize when enhanced governance review is required"],topics:["Use-case framing","Initial risk screening","Data and workflow questions","Governance routing"],exercise:"Complete a short intake for a realistic public health AI idea and recommend the appropriate review pathway."},
 {id:"int-250",code:"INT 250",title:"Environmental and Resource Impacts of AI - Considerations for Ethical Public Health Use",level:"Foundational · required for all staff",summary:"Consider energy, water, emissions, hardware, e-waste, environmental justice, proportionality, and public health value when selecting or using AI.",objectives:["Explain why environmental sustainability is part of ethical public health AI use","Recognize lifecycle resource and community-health impacts","Compare non-AI and lower-compute alternatives","Identify environmental justice and vendor-evidence questions"],topics:["AI lifecycle impacts","Energy, water, emissions, hardware, and e-waste","Environmental justice","Proportionality and lower-impact alternatives","Vendor evidence and uncertainty","Monitoring and re-review"],exercise:"Complete an Environmental and Resource Proportionality Review that compares the proposed AI approach with a non-AI and lower-compute alternative and documents affected communities, evidence gaps, safeguards, and a decision."},
 {id:"gov-100",code:"GOV 100",title:"Introduction to AI Governance for Public Health",level:"Introductory",summary:"Understand the roles, policies, decision rights, review gates, inventories, and monitoring practices that make responsible AI use governable.",objectives:["Explain why governance begins before procurement or deployment","Identify essential governance roles and decisions","Describe lifecycle oversight from intake through retirement"],topics:["Governance bodies","Risk tiers and review gates","System inventories","Monitoring and accountability"],exercise:"Map an existing agency governance process and identify where AI-specific decisions or documentation are needed."},
 {id:"gov-110",code:"GOV 110",title:"Respecting Tribal Sovereignty and Indigenous Data Governance",level:"Introductory",summary:"Recognize Tribal authority, Indigenous data-governance principles, and the need for relationship-based review when AI work involves Tribal Nations, communities, or data.",objectives:["Distinguish Tribal sovereignty from generic stakeholder engagement","Recognize limits on collection, use, sharing, and interpretation","Identify when Tribal authorization and governance are required"],topics:["Tribal sovereignty","Indigenous data governance","Authority and consent","Culturally grounded accountability"],exercise:"Review a proposed data use and identify decisions that belong to the Tribal Nation rather than the external agency or vendor."},
 {id:"com-200",code:"COM 200",title:"AI for Public Health Communications and Message Development",level:"Applied foundational",summary:"Use AI as a drafting aid while protecting accuracy, trust, scientific integrity, accessibility, and human accountability.",objectives:["Select appropriate low-risk communication tasks","Verify claims, citations, tone, and audience fit","Maintain named human approval for public-facing content"],topics:["Responsible drafting","Evidence verification","Misinformation risk","Public transparency"],exercise:"Review an AI-assisted message using an accuracy, source, equity, readability, and approval checklist."},
 {id:"com-210",code:"COM 210",title:"AI-Assisted Translation, Language Access, and Readability Review",level:"Applied foundational",summary:"Use AI carefully in translation and readability work while preserving qualified human review and meaningful language access.",objectives:["Recognize risks in automated translation","Plan review by qualified speakers and community representatives","Evaluate readability without erasing cultural meaning"],topics:["Language access","Translation limitations","Readability","Accessibility and community review"],exercise:"Compare an AI-assisted translation with a qualified human review and document corrections, unresolved terms, and approval."}
];
const foundationCourseUpdates={
 "int-100":{objectives:["Describe how CDC's four AI strategy pillars connect adoption, public trust, data platforms, and workforce capability"],topics:["CDC FY 2026–2030 AI Strategy"],exercise:"Identify one workflow where AI may help and one where it should not be used without substantial safeguards; connect the decision to one or more CDC strategy pillars."},
 "int-105":{objectives:["Explain why data may require protection even when HIPAA does not apply"],topics:["HIPAA applicability versus broader privacy safeguards","Vendor retention and model training"],exercise:"Review scenarios involving surveillance narratives, clinic information, Medicaid data, and public communications; document the safe action, prohibited action, and escalation path for each."},
 "int-200":{objectives:["Document data authority, permitted purpose, vendor processing, agentic autonomy, sustainability, and measurable public health value","Recognize when Tool 10 or enhanced governance review is required"],topics:["Data authority and permitted purpose","Vendor and cloud processing","Agentic permissions and human gates"],exercise:"Complete a short intake for a realistic public health AI idea, identify whether Tool 10 is required, and recommend the appropriate review pathway."},
 "gov-100":{objectives:["Apply risk-proportionate review","Distinguish governance from named legal, privacy, security, equity, records, and program authority"],topics:["CDC governance and public trust pillar","Risk-proportionate third-party review"],exercise:"Map an existing agency governance process; name who decides legal, privacy, security, equity, records, procurement, and program questions; and identify missing AI review gates."}
};
modules.forEach(module=>{const update=foundationCourseUpdates[module.id];if(!update)return;["objectives","topics"].forEach(key=>update[key].forEach(item=>{if(!module[key].includes(item))module[key].push(item)}));module.exercise=update.exercise;module.reviewed="2026-08-18";});

const paths=[
 ["Executive Leadership","Strategy, investment decisions, risk appetite, accountability, and public trust."],["Governance and Security","Policy, intake, risk review, privacy, cybersecurity, incident response, and oversight."],["Program Management","Use-case development, business analysis, planning, change, implementation, and evaluation."],["Epidemiology","Surveillance, analytic judgment, validation, bias, causal reasoning, and responsible decision support."],["Communications","Message development, misinformation, translation, accessibility, transparency, and review."],["Policy","Legal and policy landscapes, authority, liability, civil rights, procurement, and regulatory readiness."],["Operations and Data Quality","Workflow improvement, automation, data quality, monitoring, sustainment, and operational controls."],["Technical Architecture","Data modernization, pipelines, interoperability, RAG, architecture, secure integration, and MLOps."],["Analytics and Modeling","Model development, validation, NLP, synthetic data, subgroup performance, and monitoring."],["Health Education","Health literacy, learning design, community communication, behavioral considerations, and accessibility."]
];
const subnav=document.createElement("link");subnav.rel="stylesheet";subnav.href="subnav.css";document.head.appendChild(subnav);
const catalog=document.querySelector("#module-catalog");if(catalog)catalog.innerHTML=`<div class="catalog-heading"><p class="eyebrow">Nine core modules</p><h2>Required foundation for the public health workforce</h2></div><div class="module-grid">${modules.map((m,i)=>`<article><div class="module-meta"><span>${String(i+1).padStart(2,"0")}</span><b>${m.code}</b></div><h3><a href="module.html?id=${m.id}">${m.title}</a></h3><p>${m.summary}</p><small>${m.level}</small><a class="module-link" href="module.html?id=${m.id}">Open module overview →</a></article>`).join("")}</div>`;
const trainingGrid=document.querySelector("#training-grid");if(trainingGrid)trainingGrid.innerHTML=`<div class="catalog-heading"><p class="eyebrow">Release curriculum</p><h2>Role-based and functional paths</h2></div><div class="training-cards">${paths.map(([title,text])=>`<article><span>Not yet released</span><h3><a href="training-path.html?path=${encodeURIComponent(title)}">${title}</a></h3><p>${text}</p><a href="training-path.html?path=${encodeURIComponent(title)}">View path details →</a></article>`).join("")}</div>`;
const moduleMain=document.querySelector("#module-main");if(moduleMain){const id=new URLSearchParams(location.search).get("id")||modules[0].id;const m=modules.find(x=>x.id===id)||modules[0];const i=modules.indexOf(m);document.title=`${m.title} | Public Health AI Playbook`;moduleMain.innerHTML=`<section class="page-hero"><p class="eyebrow">Core learning · ${m.code}</p><h1>${m.title}</h1><p>${m.summary}</p></section><div class="module-layout"><article class="page-panel"><h2>Learning objectives</h2><ul>${m.objectives.map(x=>`<li>${x}</li>`).join("")}</ul><h2>Topics covered</h2><ul>${m.topics.map(x=>`<li>${x}</li>`).join("")}</ul><h2>Practical application</h2><p>${m.exercise}</p><div class="module-notice"><b>Launch format</b><p>This page provides the public module overview. The complete lesson, knowledge check, practical exercise, and downloadable training materials will be released according to the launch plan.</p></div></article><aside><section class="page-panel"><p class="eyebrow">Module information</p><p><b>Audience</b><br>All public health staff and supervisors</p><p><b>Level</b><br>${m.level}</p><p><b>Path</b><br>Shared foundational learning</p><a class="button primary" href="index.html#updates">Get training updates</a></section><section class="page-panel"><h2>Review this module</h2><p>Apply for early access to pre-release learning materials and help assess clarity, role fit, and practical value.</p><a href="reviewer.html">Become an early reviewer →</a></section></aside></div><nav class="pager">${i>0?`<a href="module.html?id=${modules[i-1].id}">← Previous module</a>`:"<span></span>"}<a href="learning.html">All core modules</a>${i<modules.length-1?`<a href="module.html?id=${modules[i+1].id}">Next module →</a>`:"<span></span>"}</nav>`}
