document.head.insertAdjacentHTML("beforeend", '<link rel="stylesheet" href="foundation-content.css?v=20260820-mobile-layout-v3">');
const learningIntro = document.querySelector(".learning-intro");
if (learningIntro) learningIntro.insertAdjacentHTML("afterend", `<section class="page panel playbook-overview learning-guidance">
  <p class="eyebrow">How learning works</p><h2>Move from shared understanding to responsible workplace practice</h2>
  <div class="overview-grid"><article class="mini-card"><h3>Start with common language</h3><p>Complete the foundational modules before role specialization so staff share vocabulary, safe-use boundaries, public health context, and escalation expectations.</p></article><article class="mini-card"><h3>Learn through public health examples</h3><p>Each module connects concepts to realistic workflows, affected populations, human decisions, and safeguards—not generic technology demonstrations.</p></article><article class="mini-card"><h3>Practice and check understanding</h3><p>Use learning objectives, knowledge checks, scenarios, and practical exercises to demonstrate understanding and identify questions requiring local policy or governance review.</p></article><article class="mini-card"><h3>Apply learning by responsibility</h3><p>Role-based and functional paths align learning with leadership, governance, programs, epidemiology, communications, policy, operations, data, and technical responsibilities.</p></article></div>
  <h2>Recommended sequence</h2><ol><li>Complete the eight shared Foundation modules.</li><li>Discuss department-approved tools, prohibited data, human-review expectations, and escalation routes.</li><li>Select additional paths based on actual responsibilities and AI-supported workflows.</li><li>Complete a practical application and document questions or safeguards requiring follow-up.</li><li>Refresh learning when policies, systems, roles, risks, or evidence change.</li></ol>
  <p><strong>Completion:</strong> viewing a module is not the same as demonstrated readiness. Organizations should combine knowledge checks with practical application, supervisor or facilitator review, and workplace evidence appropriate to the role.</p>
</section>`);

const pathsCta = document.querySelector(".paths-cta");
if (pathsCta) {
  const trackDetails = [
    ["Public Health Executive Leadership", "Health officers, deputies, CIOs, CTOs, chief data officers, division directors, bureau chiefs, and executive sponsors.", "Strategic direction, governance authority, portfolio decisions, investment, risk appetite, workforce strategy, sustainability, public accountability, and crisis response."],
    ["Governance and Security", "Governance members, privacy officers, legal counsel, procurement, cybersecurity, compliance, IT leadership, program leaders, and executives.", "Governance charters, decision rights, risk appetite, procurement, privacy, security, audit readiness, third-party risk, transparency, community oversight, and lifecycle governance."],
    ["Program Management", "Project and program managers, implementation leads, product owners, grant managers, and PMO staff.", "Use-case intake, requirements, procurement, project planning, vendor implementation, change management, monitoring, funding, and sustainment."],
    ["Epidemiology", "Epidemiologists, surveillance staff, outbreak response teams, public health analysts, and informatics epidemiologists.", "Surveillance, case investigation, signal review, outbreak detection, risk stratification, geospatial analysis, validation, uncertainty, bias, and response prioritization."],
    ["Communications", "Communications officers, public information officers, health educators, community engagement staff, and digital content staff.", "Responsible drafting, evidence review, misinformation, translation, accessibility, public transparency, and community-feedback analysis."],
    ["Policy", "Policy and legislative affairs staff, legal and policy analysts, privacy partners, planners, and agency leaders.", "Policy landscapes, authority, liability, civil rights, regulatory readiness, procurement, and public accountability."],
    ["Operations and Data Quality", "Program operations, data quality, surveillance operations, implementation, informatics, and quality-improvement staff.", "Workflow readiness, data quality, SOPs, usability, user acceptance testing, operational controls, monitoring, value measurement, and continuous improvement."],
    ["Technical Architecture", "Informaticians, technical product owners, interoperability leads, IT staff, system analysts, data modernization teams, and technical project teams.", "Data pipelines, APIs, interoperability, cloud environments, secure integration, system-of-record requirements, RAG, agentic workflows, architecture, and MLOps."],
    ["Analytics and Modeling", "Epidemiologists, analysts, data scientists, surveillance staff, evaluators, and informatics staff.", "Machine learning, predictive analytics, geospatial AI, time-series analysis, NLP, validation, causal inference, uncertainty, equity evaluation, and model monitoring."],
    ["Health Education", "Health educators, learning designers, workforce-development staff, community engagement teams, and supervisors.", "Health literacy, learning design, community communication, behavioral considerations, accessibility, and responsible workforce application."]
  ];
  pathsCta.insertAdjacentHTML("beforebegin", `<section class="page panel learning-tracks-catalog"><p class="eyebrow">Learning tracks</p><h2>Continue from a shared foundation into role-based and functional learning</h2><p>Learning tracks available through Organizational and Enterprise access organize modules by the decisions, workflows, and safeguards associated with each role. Learners begin with shared foundational learning, then follow one or more tracks based on their responsibilities. Completion combines required modules, knowledge checks, and practical workplace artifacts—not viewing alone.</p><p class="callout"><strong>Availability:</strong> These courses have been developed and are available through Organizational or Enterprise access. They are not included with the Foundation Edition.</p><div class="training-cards">${trackDetails.map(([title, audience, focus]) => `<article><span>Available in other editions</span><h3><a href="training-path.html?path=${encodeURIComponent(title)}">${title}</a></h3><p><strong>Audience:</strong> ${audience}</p><p><strong>Focus:</strong> ${focus}</p><a href="training-path.html?path=${encodeURIComponent(title)}">View Foundation path overview →</a></article>`).join("")}</div></section>`);
  const label = pathsCta.querySelector(".eyebrow");
  const paragraph = pathsCta.querySelector("p:not(.eyebrow)");
  if (label) label.textContent = "Available in other editions";
  if (paragraph) paragraph.textContent = "Completed role-based paths help public health teams build capabilities relevant to their responsibilities. Foundation readers can review the path structure and request organizational access.";
}
document.querySelectorAll(".training-cards span").forEach(label => { label.textContent = "Available in other editions"; });
const moduleNotice = document.querySelector(".module-notice p");
if (moduleNotice) moduleNotice.textContent = "This page provides the public module overview. The complete lesson, knowledge check, practical exercise, and downloadable training materials are complete and available through organizational release pathways.";
if (typeof normalizeFoundationModuleTerminology === "function") normalizeFoundationModuleTerminology();
