const groups=[
 {title:"Public health–specific U.S. foundations",intro:"The closest non-commercial resources to the Playbook's intended users and operating context.",items:[
 ["CDC AI Strategy (FY 2026–2030)","Federal public health direction spanning adoption, governance and trust, enterprise data platforms, workforce capability, and partnerships.","Anchors strategic alignment and the Plan–Build–Deploy–Govern lifecycle.","Plays 1–3, 5, 9, 11–13","https://www.cdc.gov/ai/strategy/index.html"],
 ["CDC Considerations for Generative AI in Public Health","Practical considerations for state, tribal, local, and territorial agencies, including leadership, secure tools, policy, training, human oversight, and monitoring.","Directly informs safeguards, governance gates, staff learning, and adoption sequencing.","Plays 1–3, 5–7, 10–13","https://www.cdc.gov/ai/resources/considerations-for-genai-in-public-health.html"],
 ["CDC AI Resources for Public Health Partners","Current CDC collection covering generative AI, agentic research, and disclosure in scientific work.","Supports scientific integrity, disclosure, verification, and responsible research workflows.","Plays 3, 5, 11–13","https://www.cdc.gov/ai/resources/index.html"],
 ["CDC Public Health Data Strategy","National data modernization priorities, milestones, interoperability, readiness, and AI integration.","Informs data readiness, shared infrastructure, dependencies, and implementation roadmaps.","Plays 2, 8, 9, 11, 13","https://www.cdc.gov/public-health-data-strategy/"],
 ["HHS Artificial Intelligence Strategy v3","Current department-wide strategy for governance, shared infrastructure, workforce, reproducible science, health care, and public health.","Provides federal alignment and outcome categories above the agency level.","Plays 1–3, 5, 9, 11–13","https://www.hhs.gov/sites/default/files/hhs-artificial-intelligence-strategy.pdf"],
 ["ASTHO: AI in Public Health","State and territorial resource hub with policy, risk mitigation, legal mapping, research, and implementation learning.","Supports state-agency context, legal scanning, governance, procurement, and field examples.","Plays 1–4, 7, 11–13","https://www.astho.org/topic/ai-in-public-health/"],
 ["NACCHO: AI adoption and readiness in local health departments","Local public health findings on adoption, readiness, barriers, policy, workforce, and support needs.","Grounds readiness domains and packaging in local agency realities.","Plays 2–7, 10","https://www.naccho.org/blog/articles/ai-adoption-ohio-lhds"],
 ["NACCHO 2024 Public Health Informatics Profile","National local-health informatics capacity findings, including current and anticipated AI use.","Provides readiness context for data, workforce, and infrastructure assumptions.","Plays 2, 5, 9, 11","https://www.naccho.org/uploads/downloadable-resources/2024-Public-Health-Informatics-Profile-Report.pdf"],
 ["Kansas Health Institute: Developing AI Policies for Public Health Organizations","Public-health-specific AI policy template and guidance developed through the PHIG technical-assistance ecosystem.","Informs policy components and review questions; agencies should adapt it rather than duplicate it unchanged.","Plays 1, 3, 4, 10, 12","https://www.khi.org/wp-content/uploads/2025/01/Developing-Artificial-Intelligence-AI-Policies-for-Public-Health-Organizations_A-Template-and-Guidance_web.pdf"],
 ["APHL Artificial Intelligence initiative","Laboratory AI resources, readiness findings, learning network, use cases, and responsible-adoption activities.","Adds laboratory-specific workforce, quality, validation, data, and operational considerations.","Plays 2, 5, 7, 11–13","https://aphl.org/focus-areas/QSA/analytics/artificial-intelligence"],
 ["CSTE: Applications of AI to Disease Surveillance","Accessible workforce learning on AI methods and disease-surveillance applications.","Provides surveillance examples and competency signals without treating examples as outcome evidence.","Plays 5, 7, 11, 13","https://learning.cste.org/webinar/applications-of-artificial-intelligence-to-disease-surveillance/"],
 ["NNPHI: AI and Public Health initiatives","National activity including AIxPH, peer learning, policy alignment, and practical use-case exploration.","Informs peer learning, partnerships, reviewer recruitment, field sensing, and dissemination.","Plays 4–6, 10, 13","https://nnphi.org/partner-with-us/emerging-areas-in-public-health/"],
 ["ASPPH AI Framework Report","Framework for responsible AI across public health education, research, practice, and policy.","Supports human-centered principles, competencies, missing-voices analysis, bridge roles, and transparency.","Plays 1–7, 11–13","https://aspph.org/initiatives/ai-for-public-health/ai-framework-report/"],
 ["PHAB Standards and Measures","Accreditation and quality-improvement foundation for governmental public health organizations.","Connects AI work to performance management, workforce, governance, and community accountability.","Plays 2–6, 9, 12–13","https://phaboard.org/accreditation-recognition/version-2022/"]]},
 {title:"Cross-government and nonprofit implementation frameworks",intro:"Not public-health-specific, but useful for governance, readiness, accountability, procurement, and assessment.",items:[
 ["NIST AI Risk Management Framework and Playbook","Voluntary lifecycle framework organized around Govern, Map, Measure, and Manage.","Primary risk backbone; the toolkit supplies public health context and local implementation.","All plays, especially 1–3, 7, 11–13","https://www.nist.gov/itl/ai-risk-management-framework/ai-risk-management-framework-resources"],
 ["NIST Generative AI Profile","Companion profile addressing risks unique to or intensified by generative AI.","Informs risk identification, testing, provenance, incident handling, and monitoring.","Plays 3, 7, 11–13","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"],
 ["U.S. GAO AI Accountability Framework","Government framework organized around governance, data, performance, and monitoring, with audit questions and evidence.","Strengthens audit readiness, documentation, evaluation, and evidence artifacts.","Plays 3, 9, 11–13","https://www.gao.gov/artificial-intelligence"],
 ["MITRE AI Maturity Model and Assessment Tool Guide","Nonprofit organizational model covering adoption, resources, workforce, enterprise goals, and maturity progression.","Readiness comparator; the Playbook adds public-health-specific domains and action routing.","Plays 2, 5, 9, 12–13","https://www.mitre.org/news-insights/publication/mitre-ai-maturity-model-and-organizational-assessment-tool-guide"],
 ["Health AI Partnership: AI Vendor Disclosure Framework","Community-informed vendor questions across intended use, evidence, data stewardship, equity, workflow, monitoring, and accountability.","Useful procurement comparator requiring adaptation from health-care delivery to governmental public health.","Plays 7–8, 11–13","https://healthaipartnership.org/haip-ai-vendor-disclosure-framework"],
 ["Health Equity Across the AI Lifecycle (HEAAL)","Framework for equity review at key health-AI adoption decisions.","Strengthens equity checks; transferability to governmental public health must be assessed.","Plays 4, 7, 11–13","https://healthaipartnership.org/health-equity-across-the-ai-lifecycle-heaal"],
 ["ONC HTI-1 Algorithm Transparency resources","Federal transparency requirements for predictive decision support in certified health IT.","Provides a useful transparency model when public health interfaces with certified health IT; applicability varies.","Plays 3, 8, 11–13","https://healthit.gov/regulations/hti-rules/hti-1-final-rule/"]]},
 {title:"Global health, ethics, and human-rights foundations",intro:"Broadly recognized ethics, governance, readiness, rights, equity, and sustainability principles.",items:[
 ["WHO: Ethics and Governance of AI for Health","Global health-sector guidance centered on ethics, human rights, accountability, inclusiveness, transparency, safety, and sustainability.","Foundational principles and lifecycle safeguards; local translation is required.","Plays 1, 3–4, 7, 11–13","https://www.who.int/publications/i/item/9789240029200"],
 ["WHO: Regulatory Considerations on AI for Health","Considerations for intended use, documentation, validation, data quality, privacy, collaboration, and lifecycle management.","Supports regulatory awareness, vendor evidence, validation, and change control.","Plays 3, 7–8, 11–13","https://iris.who.int/handle/10665/373421"],
 ["PAHO: Artificial Intelligence for Health","Regional collection of readiness, public health guidance, ethics, governance, and technical documentation.","Adds a regional and international public-health-readiness perspective.","Plays 1–5, 7, 11–13","https://www.paho.org/en/artificial-intelligence-health"],
 ["OECD AI Principles","Intergovernmental principles for innovative, trustworthy AI respecting human rights and democratic values.","Supports vision and policy alignment; operational controls come from other sources.","Plays 1, 3–4, 12","https://oecd.ai/en/ai-principles"],
 ["UNESCO Recommendation on the Ethics of Artificial Intelligence","Global normative framework covering rights, inclusion, governance, education, environment, culture, and impact assessment.","Strengthens environmental, cultural, accessibility, inclusion, literacy, and community-impact dimensions.","Plays 1, 3–5, 7, 11–13","https://www.unesco.org/en/legal-affairs/recommendation-ethics-artificial-intelligence"]]},
 {title:"Complementary evidence and technical reference",intro:"Deepens technical evaluation and evidence literacy without replacing organizational implementation planning.",items:[
 ["The Public Health AI Handbook","Open handbook covering applications, technical evaluation, coding, model and vendor assessment, safety, failures, and emerging practice.","Complementary technical reference; the Playbook focuses on organizational strategy, sequencing, workforce, governance, and change.","Across plays; especially 7, 11, and 13","https://publichealthaihandbook.com/"]]}
];
const root=document.querySelector('#resource-groups');
root.innerHTML=groups.map(g=>`<section class="resource-group"><h2>${g.title}</h2><p>${g.intro}</p><div class="resource-grid">${g.items.map(([title,summary,use,plays,url])=>`<article class="resource-card"><h3><a href="${url}" target="_blank" rel="noopener noreferrer">${title}</a></h3><p>${summary}</p><p class="use"><b>Toolkit use:</b> ${use}</p><span class="plays">${plays}</span></article>`).join('')}</div></section>`).join('')+`<p class="scope-note"><b>Scope note.</b> This is a structured audit of major publicly available, non-commercial resources relevant to organizational AI readiness and implementation in public health as of August 13, 2026. It does not claim to capture every publication, jurisdictional policy, academic program, conference session, or local practice example worldwide. Submit additions through the <a href="feedback.html"><u>feedback page</u></a>.</p>`;
const resourceReviewMeta=document.querySelector('.resource-meta');
if(resourceReviewMeta) root.insertAdjacentElement('afterend',resourceReviewMeta);
