const reviewerMember = (() => { try { return JSON.parse(localStorage.getItem("foundation-member-profile") || "null"); } catch { return null; } })();
const reviewerForm = document.querySelector("[data-demo-form]");
document.querySelector(".form-shell")?.insertAdjacentHTML("beforebegin", '<section class="panel reviewer-benefits-panel"><div class="section-heading"><p class="eyebrow">Reviewer program</p><h2>Reviewer benefits</h2><p>Free members may apply for structured reviews matched to their experience. Selection depends on topic fit, perspective balance, and available review capacity.</p></div><div class="four-grid"><article><h3>Early access</h3><p>See selected new plays, tools, or learning resources before public release.</p></article><article><h3>Professional learning</h3><p>Learn from practical public health scenarios, structured review questions, and emerging implementation issues.</p></article><article><h3>Visible contribution</h3><p>Receive optional acknowledgment, with permission, for completed review contributions.</p></article><article><h3>Field influence</h3><p>Help improve clarity, usability, evidence, accessibility, role fit, and public health relevance.</p></article></div></section>');
if (reviewerForm && !reviewerMember) {
  reviewerForm.querySelectorAll("input, select, textarea, button").forEach(control => control.disabled = true);
  reviewerForm.insertAdjacentHTML("afterbegin", '<div class="wide member-status locked"><strong>Free membership is required before applying to review new tools.</strong><br><a class="btn primary small" href="account.html">Create free account</a></div>');
} else if (reviewerForm && reviewerMember) {
  const pairs = { name: [reviewerMember.firstName, reviewerMember.lastName].filter(Boolean).join(" "), email: reviewerMember.email, organization: reviewerMember.organization, role: reviewerMember.role };
  Object.entries(pairs).forEach(([name, value]) => { const field = reviewerForm.elements.namedItem(name); if (field && value) field.value = value; });
}
